import MarkdownDocument from '../markdown-document'
import Type from './type'

export default class Role extends MarkdownDocument {

    constructor(readonly type: Type, readonly name: string, protected readonly _filename: string = name.toLowerCase()) {
        super(name, _filename)
    }

    protected _base_url = '/docs/roles'

    static readonly ARCHIVISTE = new Role(Type.VILLAGEOIS, 'Archiviste')
    static readonly ASSASSIN = new Role(Type.SBIRE, 'Assassin')
    static readonly AUBERGISTE = new Role(Type.VILLAGEOIS, 'Aubergiste')
    static readonly AVOCAT_DU_DIABLE = new Role(Type.SBIRE, 'Avocat du Diable', 'avocat-du-diable')
    static readonly BARBIER = new Role(Type.ETRANGER, 'Barbier')
    static readonly BARON = new Role(Type.SBIRE, 'Baron')
    static readonly BRUTE = new Role(Type.ETRANGER, 'Brute')
    static readonly CHASSEUR_DE_PRIMES = new Role(Type.VILLAGEOIS, 'Chasseur de primes', 'chasseur-de-primes')
    static readonly CHEF_DE_SECTE = new Role(Type.VILLAGEOIS, 'Chef de Secte', 'chef-de-secte')
    static readonly COMMERE = new Role(Type.VILLAGEOIS, 'Commère', 'commere')
    static readonly CONSPIRATEUR = new Role(Type.SBIRE, 'Conspirateur')
    static readonly COURTISANE = new Role(Type.VILLAGEOIS, 'Courtisane')
    static readonly CRIEUR = new Role(Type.VILLAGEOIS, 'Crieur')
    static readonly CROQUE_MORT = new Role(Type.VILLAGEOIS, 'Croque-Mort', 'croque-mort')
    static readonly CROQUEUSE_D_HOMMES = new Role(Type.SBIRE, 'Croqueuse d\'hommes', 'croqueuse-d-hommes')
    static readonly CUISTOT = new Role(Type.VILLAGEOIS, 'Cuistot')
    static readonly EMPATHIQUE = new Role(Type.VILLAGEOIS, 'Empathique')
    static readonly EMPOISONNEUR = new Role(Type.SBIRE, 'Empoisonneur')
    static readonly ENQUETEUR = new Role(Type.VILLAGEOIS, 'Enquêteur', 'enqueteur')
    static readonly ERMITE = new Role(Type.ETRANGER, 'Reclus')
    static readonly EXORCISTE = new Role(Type.VILLAGEOIS, 'Exorciste')
    static readonly FAUSSAIRE = new Role(Type.VILLAGEOIS, 'Faussaire')
    static readonly FEMME_DE_CHAMBRE = new Role(Type.VILLAGEOIS, 'Femme de Chambre', 'femme-de-chambre')
    static readonly FOU = new Role(Type.VILLAGEOIS, 'Fou')
    static readonly GARDIEN = new Role(Type.VILLAGEOIS, 'Gardien')
    static readonly GITANE = new Role(Type.ETRANGER, 'Gitane')
    static readonly LAVANDIERE = new Role(Type.VILLAGEOIS, 'Lavandière', 'lavandiere')
    static readonly HERBORISTE = new Role(Type.VILLAGEOIS, 'Herboriste')
    static readonly IMP = new Role(Type.DEMON, 'Imp')
    static readonly INVENTEUR = new Role(Type.ETRANGER, 'Inventeur')
    static readonly LUNATIQUE = new Role(Type.ETRANGER, 'Lunatique')
    static readonly MAIRE = new Role(Type.VILLAGEOIS, 'Maire')
    static readonly MAJORDOME = new Role(Type.ETRANGER, 'Majordome')
    static readonly MAMIE = new Role(Type.VILLAGEOIS, 'Mamie')
    static readonly MARIN = new Role(Type.VILLAGEOIS, 'Marin')
    static readonly MENESTREL = new Role(Type.VILLAGEOIS, 'Ménestrel', 'menestrel')
    static readonly MERCENAIRE = new Role(Type.VILLAGEOIS, 'Mercenaire')
    static readonly MOINE = new Role(Type.VILLAGEOIS, 'Moine')
    static readonly PACIFISTE = new Role(Type.VILLAGEOIS, 'Pacifiste')
    static readonly PARIEUR = new Role(Type.VILLAGEOIS, 'Parieur')
    static readonly PARRAIN = new Role(Type.SBIRE, 'Parrain')
    static readonly PO = new Role(Type.DEMON, 'Po', 'po')
    static readonly POLITICIEN = new Role(Type.ETRANGER, 'Politicien')
    static readonly PUKKA = new Role(Type.DEMON, 'Pukka')
    static readonly PREDICATEUR = new Role(Type.VILLAGEOIS, 'Predicateur')
    static readonly PROFESSEUR = new Role(Type.VILLAGEOIS, 'Professeur')
    static readonly PTIT_MONSTRE = new Role(Type.DEMON, 'P\'tit Monstre', 'ptit-monstre')
    static readonly PUCELLE = new Role(Type.VILLAGEOIS, 'Pucelle')
    static readonly SHABALOTH = new Role(Type.DEMON, 'Shabaloth')
    static readonly SOLDAT = new Role(Type.VILLAGEOIS, 'Soldat')
    static readonly SORCIERE = new Role(Type.SBIRE, 'Sorcière', 'sorciere')
    static readonly SOULARD = new Role(Type.ETRANGER, 'Soûlard', 'soulard')
    static readonly TRAITRE = new Role(Type.SBIRE, 'Espion', 'espion')
    static readonly VERTUEUX = new Role(Type.ETRANGER, 'Vertueux')
    static readonly VOYANTE = new Role(Type.VILLAGEOIS, 'Voyante')
    static readonly ZOMBUUL = new Role(Type.DEMON, 'Zombuul')
}
